apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: ghcr.io/tyvik/everypay-mock:sha-c7fe153
      ports:
        - name: http
          containerPort: 8000
      envFrom:
        - configMapRef:
            name: everypay-config
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: everypay-secrets
              key: POSTGRES_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: everypay-secrets
              key: SECRET_KEY
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
